### ISSUE TITLE
Using argparse

### ISSUE THREAD

**Issue by kenokenobingo** [BauhausUniversity/cuttlefish#3]
Maybe it’s easier to use the [argparse](https://docs.python.org/3/library/argparse.html) library for parsing command line arguments: https://stackoverflow.com/questions/11604653/add-command-line-arguments-with-flags-in-python3#11604777. What do you think, @mxa?

![Parsing](https://i.giphy.com/media/hXYlYBixtHEFq/giphy.webp)

**Comment by mxa** [comment]
Oh, we just took the first code example I found, but this indeed looks much cleaner. Please make a PR

**Comment by kenokenobingo** [comment]
Will do!

**Comment by mxa** [comment]
closed with https://github.com/BauhausUniversity/cuttlefish/commit/871f8225250e5bb6a8a4a1aeb45f4051456d9cc0
