### ISSUE TITLE
find_word.py: Automatically cutting videos using ffmpeg

### ISSUE THREAD

**Issue by kenokenobingo** [BauhausUniversity/cuttlefish#4]
Will work on a pull request.

![Cutting](https://i.giphy.com/media/b5Hcaz7EPz26I/giphy.webp)

**Comment by mxa** [comment]
Alternatively https://github.com/gpac/gpac is cool too.

**Comment by mxa** [comment]
Design consideration: right now we have "debug output" by default reiterating the flags. For simpler use with other tools, I'd suggest to remove the debug output (or only show it if a -v --verbose flag is set)

**Comment by mxa** [comment]
Any progress?

**Comment by kenokenobingo** [comment]
I’ve already implemented cutting, using `ffmpeg-python` again, cf. #7.
